/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.st.ui;

import com.st.beans.MasterItemBean;
import com.st.beans.MasterItemTypeBean;
import com.st.process.MasterItemProcessor;
import com.st.utils.Constants;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Timothy_Fab
 */
public class MasterItemList extends javax.swing.JFrame 
{
  /** Table Variable. */
  /** Item Type Info column size. */
  private final int ITEMINFO_COLSIZE = 3;
  /** Default table model for the Item Lookup. */
  private DefaultTableModel tm = null;
  
  /** Column Title - ID. */
  private final String COLTITLE_ID = "Kode #";
  /** Column Title - Name. */
  private final String COLTITLE_NAME = "Nama";
  /** Column Title - Item Type. */
  private final String COLTITLE_TYPE = "Tipe";
  /** Column Title - Item Type. */
  private final String COLTITLE_SELLPRICE = "Harga Jual";
  /** Column Title - Item Type. */
  private final String COLTITLE_BUYPRICE = "Harga Beli";
  /** Column Title - Item Type. */
  private final String COLTITLE_DATE = "Tanggal Ubah";
  /** Column Title - Item Type. */
  private final String COLTITLE_USER = "User Ubah";
  
  /** Column position for Item Info ID. */
  private final int ITEMTYPE_COL_ID = 0;
  /** Column position for Item Info Name. */
  private final int ITEMTYPE_COL_NAME = 1;
  /** Column position for Item Type. */
  private final int ITEMTYPE_COL_TYPE = 2;
  /** Column position for Item Type. */
  private final int ITEMTYPE_COL_SELLP = 3;
  /** Column position for Item Type. */
  private final int ITEMTYPE_COL_BUYP = 4;
  /** Column position for Item Type. */
  private final int ITEMTYPE_COL_DATE = 5;
  /** Column position for Item Type. */
  private final int ITEMTYPE_COL_USER = 6;
  
  MasterItemBean[] dataItemType = null;
  MasterItemEdit itemEditUI = null;
  
  /** master item proc. */
  private MasterItemProcessor p = null;
  
  /**
   * Creates new form MasterItemList
   */
  public MasterItemList() 
  {
    initComponents();
    this.SearchItem();
    setExtendedState(MAXIMIZED_BOTH);
  }

  private void SearchItem()
  {
    //Searching List Item type.
    int searchBy = cmbSearchCriteria.getSelectedIndex();
    MasterItemBean[] res;

    //SvrUtilities.isDebug = true;
    if(null==p) p = new MasterItemProcessor();
    System.out.println("SEARCH BY: " + searchBy);
    switch(searchBy)
    {
      case 0://Search by item id
        res = p.getItemList(
                Constants.ITEMTYPE_SEARCHBY_ITEMID,
          txtSearchValue.getText(),
          null);
        break;      
      default://Search by item name
        res = p.getItemList(
            Constants.ITEMTYPE_SEARCHBY_ITEMNAME,
          txtSearchValue.getText(),
          null);
        break;
    }
    dataItemType = res;
    //Repaint the item list
    this.repaintItemTypeList(res);
  }
  
  public void editInfo(boolean action)
  {
    MasterItemBean bn;
    if(action)
    {
      int SelectedRow = tblItem.getSelectedRow();
      bn = dataItemType[SelectedRow];

      if(null!=bn)
      {
        itemEditUI = new MasterItemEdit(this, true, action, bn);
      }
    }
    else
    {
      itemEditUI = new MasterItemEdit(this, true, action, null);
    }
    
    itemEditUI.setVisible(true);
    itemEditUI.toFront();
    
    //after transaction is finish, reload
    itemEditUI.finalizeMe();
    this.SearchItem();
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    btnAdd = new javax.swing.JButton();
    btnExit = new javax.swing.JButton();
    jPanel2 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    btnSearch = new javax.swing.JButton();
    cmbSearchCriteria = new javax.swing.JComboBox();
    txtSearchValue = new javax.swing.JTextField();
    jScrollPane2 = new javax.swing.JScrollPane();
    tblItem = new javax.swing.JTable();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(204, 204, 255));

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    jLabel1.setText("Master Barang");

    btnAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    btnAdd.setText("Tambah");
    btnAdd.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAddActionPerformed(evt);
      }
    });

    btnExit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    btnExit.setText("Keluar");
    btnExit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnExitActionPerformed(evt);
      }
    });

    jPanel2.setOpaque(false);

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel2.setText("CARI BARANG:");

    btnSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    btnSearch.setText("CARI");
    btnSearch.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSearchActionPerformed(evt);
      }
    });

    cmbSearchCriteria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    cmbSearchCriteria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kode Barang", "Nama Barang" }));

    txtSearchValue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(cmbSearchCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(txtSearchValue, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(1, 1, 1)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(cmbSearchCriteria)
          .addComponent(txtSearchValue)))
      .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
    );

    jScrollPane2.setOpaque(false);

    tblItem.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    tblItem.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tblItemMouseClicked(evt);
      }
    });
    jScrollPane2.setViewportView(tblItem);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addContainerGap(616, Short.MAX_VALUE)
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(574, 574, 574))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(21, 21, 21)
        .addComponent(btnAdd)
        .addGap(18, 18, 18)
        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane2)
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnAdd)
          .addComponent(btnExit))
        .addGap(41, 41, 41))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
    this.CloseMe();
  }//GEN-LAST:event_btnExitActionPerformed

  private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
    this.SearchItem();
  }//GEN-LAST:event_btnSearchActionPerformed

  private void tblItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItemMouseClicked
    editInfo(true);
  }//GEN-LAST:event_tblItemMouseClicked

  private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    editInfo(false);
  }//GEN-LAST:event_btnAddActionPerformed

  private void repaintItemTypeList(MasterItemBean[] res)
  {
    if(null==res || res.length<=0) return;

    this.resetItemTypeList(res.length);
    
    /* This is the row:
     * ID | NAME | STD SELL PRICE
     */
    //Set the items into the shopping list table.
    for(int i=0; i<res.length; i++)
    {
      //System.out.println("ROW " + i + ":" + res[i].getItemID() + "=" + res[i].getItemName() + "=" + res[i].getMailCity());
      tm.setValueAt(res[i].getId(), i, ITEMTYPE_COL_ID);
      tm.setValueAt(res[i].getName(), i, ITEMTYPE_COL_NAME);
      tm.setValueAt(res[i].getItemType(), i, ITEMTYPE_COL_TYPE);
      tm.setValueAt(res[i].getSalesPrice(), i, ITEMTYPE_COL_SELLP);
      tm.setValueAt(res[i].getPurchasePrice(), i, ITEMTYPE_COL_BUYP);
      tm.setValueAt(res[i].getEntryDate(), i, ITEMTYPE_COL_DATE);
      tm.setValueAt(res[i].getEntryUser(), i, ITEMTYPE_COL_USER);
    }
  }
  
  private void resetItemTypeList(int row)
  {
    TableColumn t;

    int COLSIZE_ID = 100;
    int COLSIZE_NAME = 300;
    int COLSIZE_TYPE = 400;
    int COLSIZE_SELL = 100;
    int COLSIZE_BUY = 100;
    int COLSIZE_DATE = 100;
    int COLSIZE_USER = 100;
    
    tm = new DefaultTableModel(row, ITEMINFO_COLSIZE);
    tm.setColumnIdentifiers(
      new String[]
      {
        COLTITLE_ID,
        COLTITLE_NAME,
        COLTITLE_TYPE,
        COLTITLE_SELLPRICE,
        COLTITLE_BUYPRICE,
        COLTITLE_DATE,
        COLTITLE_USER
      }
    );
    
    tblItem.setModel(tm);
    tm.setValueAt(null, 0, ITEMTYPE_COL_ID);
    tm.setValueAt(null, 0, ITEMTYPE_COL_NAME);
    tm.setValueAt(null, 0, ITEMTYPE_COL_TYPE);
    tm.setValueAt(null, 0, ITEMTYPE_COL_SELLP);
    tm.setValueAt(null, 0, ITEMTYPE_COL_BUYP);
    tm.setValueAt(null, 0, ITEMTYPE_COL_DATE);
    tm.setValueAt(null, 0, ITEMTYPE_COL_USER);
    
    t = tblItem.getColumn(COLTITLE_ID);
    t.setResizable(false);
    t.setMinWidth(COLSIZE_ID);
    t.setPreferredWidth(COLSIZE_ID);
    
    t = tblItem.getColumn(COLTITLE_NAME);
    t.setResizable(false);
    t.setMinWidth(COLSIZE_NAME);
    t.setPreferredWidth(COLSIZE_NAME);
    
    t = tblItem.getColumn(COLTITLE_TYPE);
    t.setResizable(false);
    t.setMinWidth(COLSIZE_TYPE);
    t.setPreferredWidth(COLSIZE_TYPE);
    
    t = tblItem.getColumn(COLTITLE_SELLPRICE);
    t.setResizable(false);
    t.setMinWidth(COLSIZE_SELL);
    t.setPreferredWidth(COLSIZE_SELL);
    
    t = tblItem.getColumn(COLTITLE_BUYPRICE);
    t.setResizable(false);
    t.setMinWidth(COLSIZE_BUY);
    t.setPreferredWidth(COLSIZE_BUY);
    
    t = tblItem.getColumn(COLTITLE_DATE);
    t.setResizable(false);
    t.setMinWidth(COLSIZE_DATE);
    t.setPreferredWidth(COLSIZE_DATE);
    
    t = tblItem.getColumn(COLTITLE_USER);
    t.setResizable(false);
    t.setMinWidth(COLSIZE_USER);
    t.setPreferredWidth(COLSIZE_USER);
  }
  
  public void RefreshTable()
  { this.SearchItem(); }
  
  private void CloseMe()
  {
    int logoutResult = JOptionPane.showConfirmDialog(
                        this,
                        "Anda yakin untuk keluar?",
                        "LogoutConfirmation",
                        JOptionPane.YES_NO_OPTION);
    if(logoutResult==JOptionPane.YES_OPTION)
    {
      //Main.callModule(Constants.MOD_HOME);
      this.finalize();
    }
  }
  
  public void finalize()
  {
    this.setVisible(false);
    dispose();
    System.out.println("Make login page invisible!");
  }
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(MasterItemList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(MasterItemList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(MasterItemList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(MasterItemList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new MasterItemList().setVisible(true);
        }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAdd;
  private javax.swing.JButton btnExit;
  private javax.swing.JButton btnSearch;
  private javax.swing.JComboBox cmbSearchCriteria;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JTable tblItem;
  private javax.swing.JTextField txtSearchValue;
  // End of variables declaration//GEN-END:variables
}
