/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.st.ui;

import com.st.beans.MasterCardBean;
import com.st.process.MasterCardProcessor;
import com.st.utils.Utilities;
import javax.swing.JOptionPane;
/**
 *
 * @author Timothy_Fab
 */
public class MasterCardEdit extends javax.swing.JDialog 
{
  /** Flag used to determine action. update or create. */
  private boolean isUpdate = false;
  private boolean StatusTransaction;
  
  private MasterCardList mcl = null;
  private MasterCardProcessor mcp = null;
  
 
    
    /**
     * Creates new form MasterCardEdit
     */
    public MasterCardEdit(java.awt.Frame parent, boolean modal, boolean isUpdate, MasterCardBean bn) {
        super(parent, modal);
        this.isUpdate = isUpdate;
        initComponents();
        super.setSize(367, 390);
        this.setLocationRelativeTo(null);
       
       if(isUpdate)
       {
        txtCode.setText(bn.getCode());
        txtCard.setText(bn.getCard());
       }
    }
    
   /**
    * validate Input data
    * @return 
    */ 
  private MasterCardBean validateData()
  {
    String tmp = null;  
    MasterCardBean bn = new MasterCardBean();
    
    /** validate Code. */
    tmp = txtCode.getText();
    if(!Utilities.isEmpty(tmp))
    { bn.setCode(tmp); }
    else
    {
      JOptionPane.showMessageDialog(this, 
              "Error!", 
              "Code Tidak boleh kosong", 
              JOptionPane.ERROR_MESSAGE);
    }
    
    /** validate Card. */
    tmp = txtCard.getText();
    if(!Utilities.isEmpty(tmp))
    { bn.setCard(tmp); }
    else
    {
      JOptionPane.showMessageDialog(this, 
              "Error!", 
              "Card Tidak boleh kosong", 
              JOptionPane.ERROR_MESSAGE);
    }
     
   return bn;
  }        
    
  /** Update Process. */
  private void update()
  {
    mcp = new MasterCardProcessor();
    MasterCardBean bn = this.validateData();
    if(!mcp.update(bn))
    {
      StatusTransaction = false;
      JOptionPane.showMessageDialog(this, "Error!", "Error!!! update Master Card. ", JOptionPane.ERROR_MESSAGE);
    }
    else
    {
      StatusTransaction = true;
      JOptionPane.showMessageDialog(this, "Success!!", "Success update Master Card. ", JOptionPane.PLAIN_MESSAGE);
    }
    
    //Finalising Proc
    mcp.finalize();
    System.out.println("AFTER FINALIZE");
    this.FinishingTransaction();
  }  
  
    /** Create process. */
  private void create()
  {
    mcp = new MasterCardProcessor();
    MasterCardBean bn = this.validateData();
    if(!mcp.create(bn))
    {
      StatusTransaction = false;
      JOptionPane.showMessageDialog(this, "Error!", "Error create Master Card. ", JOptionPane.ERROR_MESSAGE);
    }
    else
    {
      StatusTransaction = true;
      JOptionPane.showMessageDialog(this, "Success!!", "Success create Master Card. ", JOptionPane.PLAIN_MESSAGE);
    }
    
    //Finalising Proc
    mcp.finalize();
    this.FinishingTransaction();
  }
  
    /** Delete process. */
  private void delete()
  {
    mcp = new MasterCardProcessor();
    MasterCardBean bn = this.validateData();
    if(!mcp.delete(bn.getCode()))
    {
      StatusTransaction = false;
      JOptionPane.showMessageDialog(this, "Error!", "Error delete master item type. ", JOptionPane.ERROR_MESSAGE);
    }
    else
    {
      StatusTransaction = true;
      JOptionPane.showMessageDialog(this, "Success!!", "Success delete master item type. ", JOptionPane.PLAIN_MESSAGE);
    }
    
    //Finalising Proc
    mcp.finalize();
    this.FinishingTransaction();
  }
  
  public void FinishingTransaction()
  {
    //If transaction success
    if(StatusTransaction)
    {
      this.setVisible(false);
      //Refresh Table.
      mcl = new MasterCardList();
      mcl.RefreshTable();
    }
  }
    
  public void finalizeMe()
  {
    StatusTransaction = false;
    if(null!=mcp) mcp = null;
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnCancel1 = new javax.swing.JButton();
        txtCode = new javax.swing.JTextField();
        txtCard = new javax.swing.JTextField();
        LCard = new javax.swing.JLabel();
        LCardCode = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Info Card");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 20, 86, 22);

        btnSave.setText("Simpan");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave);
        btnSave.setBounds(30, 300, 80, 30);

        btnCancel.setText("Keluar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel);
        btnCancel.setBounds(230, 300, 80, 30);

        btnCancel1.setText("Hapus");
        btnCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel1);
        btnCancel1.setBounds(130, 300, 80, 30);

        txtCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeActionPerformed(evt);
            }
        });
        getContentPane().add(txtCode);
        txtCode.setBounds(100, 80, 170, 30);

        txtCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCardActionPerformed(evt);
            }
        });
        getContentPane().add(txtCard);
        txtCard.setBounds(100, 140, 200, 30);

        LCard.setText("Card :");
        getContentPane().add(LCard);
        LCard.setBounds(50, 150, 34, 14);

        LCardCode.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LCardCode.setText("Kode :");
        getContentPane().add(LCardCode);
        LCardCode.setBounds(50, 90, 36, 15);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/st/ui/image/Background_edit.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 370, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeActionPerformed

    private void txtCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCardActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
      if(isUpdate)
      { update(); }
       else
      { create(); }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel1ActionPerformed
        delete();
    }//GEN-LAST:event_btnCancel1ActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterCardEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterCardEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterCardEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterCardEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MasterCardEdit dialog = new MasterCardEdit(new javax.swing.JFrame(), true, true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LCard;
    private javax.swing.JLabel LCardCode;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCancel1;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtCard;
    private javax.swing.JTextField txtCode;
    // End of variables declaration//GEN-END:variables
}
